baseURL = 'https://matu29utb.github.io/Hugo_DWES_DavidMartin'
languageCode = 'es-es'
title = 'Presentándome a la comunidad'
theme = 'relearn'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


